### ISSUE TITLE
Probable interpreter bug in export of immutable global with constant initializer

### ISSUE THREAD

**Issue by lars-t-hansen** [WebAssembly/mutable-global#10]
In linking.wast:
```
(module $Mg
  (global $glob (export "glob") i32 (i32.const 42))
  (func (export "get") (result i32) (get_global $glob))
)
...
(assert_return (get $Mg "glob") (i32.const 42))
```
assert_return uses Object.is to compare equality, but the exported value should be a WebAssembly.Global object unless I misread the draft spec, so that check can't succeed.  

The test case fails in SpiderMonkey but appears to pass in the reference interpreter, which is why I tentatively suggest an interpreter bug, but I have no further diagnosis.  It could be that assert_return should instead look more deeply into WebAssembly.Global objects.

**Comment by binji** [comment]
Yes, I think the generated JS code should be changed here. It might be simplest if the `get` accessor just unwraps `WebAssembly.Global` objects for the core tests.

**Comment by rossberg** [comment]
I agree, you need to adapt the interpreter to the extended notion of global. A `get` action in WAST should call the `get` accessor now.

**Comment by binji** [comment]
Should be fixed.
