### ISSUE TITLE
Creating an i64 WebAssembly.Global from JS

### ISSUE THREAD

**Issue by binji** [WebAssembly/mutable-global#15]
The proposal spec currently doesn't allow this:

```
new WebAssembly.Global({type: 'i64'});
```

But it seems like we should allow it, since the value will be default initialized.

I don't think we should allow this, however:

```
new WebAssembly.Global({type: 'i64'}, 0);
```

Since this relies on an implicit conversion from `Number` to i64. When we add bigint support, we can use `0n` instead, which should be OK.

Thoughts?

**Comment by jfbastien** [comment]
So we'd only allow `undefined` as the value?

**Comment by binji** [comment]
Hm, yeah. Maybe it's weird to allow this now, and we should just wait for bigint (which is coming soon™)

**Comment by lars-t-hansen** [comment]
The special case seems strange, and we don't really need it - if we need to share an i64 global variable it can be created in a module and exported.  If the module is re-instantiated every time it's used, we get a new global every time...  It's an expensive workaround but requires no special cases.

**Comment by binji** [comment]
OK, I think I changed my mind on this. Closing.
