### ISSUE TITLE
The sample has practical issue?

### ISSUE THREAD

**Issue by xwang98** [WebAssembly/mutable-global#24]
I have a question in reading the sample code below from the proposal overview. If the modules by m1Bytes and m2Bytes are compiled from sources in C/C++ or others, they usually should have different global variables memory layout in the linear memory. Will the second module instance importing the memory of the first module cause some functional problems?  If it is for the same module, then it should be fine.

```
let agentSp = new WebAssembly.Global({type: 'i32', mutable: true}, 0x100);

let imports = {env: {sp: agentSp}};
WebAssembly.instantiate(m1Bytes, {}).then(
    ({instance}) => {
        let imports = {env: {
          memory: instance.exports.memory,
          sp: agentSp,
        }};
        WebAssembly.instantiate(m2Bytes, imports).then(...);
    });
```

**Comment by binji** [comment]
The assumption here is that the tools that generated m1 and m2 are coordinating with how to lay out linear memory. Generally this could be done by having all data segments have their offset relative to an imported global variable.

**Comment by xwang98** [comment]
> Generally this could be done by having all data segments have their offset relative to an imported global variable.
This would require compiler support, right? I came up an idea about it - maybe the module loader can scan the module bytecode and add the segment offset to the "offset" immediate operand of all load/store opcodes.

**Comment by binji** [comment]
> This would require compiler support, right?

Yes, generally the compiler would compile position-independent code, so that it is easily relocatable.

> maybe the module loader can scan the module bytecode and add the segment offset to the "offset" immediate operand of all load/store opcodes.

I think that could work, but modifying wasm bytecode isn't something we normally do in a module loader.

**Comment by xwang98** [comment]
@binji thanks!
