### ISSUE TITLE
Update `index.bs` for `WebAssembly.Global`

### ISSUE THREAD

**Issue by binji** [WebAssembly/mutable-global#3]
The original proposal's JS API was written before the Bikeshed doc was landed, but has the basics: https://github.com/WebAssembly/mutable-global/blob/master/proposals/mutable-global/Overview.md#importexport-mutable-globals

**Comment by binji** [comment]
cc @littledan

**Comment by binji** [comment]
Note that the overview does not include the additional properties mentioned in https://github.com/WebAssembly/threads/issues/87.

**Comment by littledan** [comment]
You can assign this to me if you'd like (I don't have write access so I can't assign it to myself). I hope to get to it in a month or so.

**Comment by binji** [comment]
Cool, I think I might take a stab at it this week. Never written any bikeshed, so if you can review that'd be really helpful :-)

**Comment by binji** [comment]
Landed in https://github.com/WebAssembly/mutable-global/commit/46b93a4dda05863a97f534fdf636e59fa69905e7.
